package domain;

// Generated 18/12/2011 04:12:33 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Parametros generated by hbm2java
 */
@Entity
@Table(name = "parametros")
public class Parametro implements java.io.Serializable {
	
	private static final long serialVersionUID = 170525L;

	public static final String HOME_FOLDER_PARAM_NAME = "HOME_FOLDER";
	public static final String HOME_APP_FOLDER_PARAM_NAME = "HOME_APP_FOLDER";
	public static final String LOW_PRIORITY_FOLDER_PARAM_NAME = "LOW_PRIORITY_FOLDER";	
	public static final String HIGH_PRIORITY_FOLDER_PARAM_NAME = "HIGH_PRIORITY_FOLDER";	
	public static final String NOT_SENT_FOLDER_PARAM_NAME = "NOT_SENT_FOLDER";
	public static final String SENT_FOLDER_PARAM_NAME = "SENT_FOLDER";
	public static final String RECEIVED_FOLDER_PARAM_NAME = "RECEIVED_FOLDER";
	public static final String ASIGNACION_RANGO_CAE_PARAM_NAME = "ASIGNACION_RANGO_CAE";	
	public static final String SOLICITUD_RANGO_CAE_PARAM_NAME = "SOLICITUD_RANGO_CAE";
	public static final String SOLICITUD_RANGO_NO_ASIGNADO_PARAM_NAME = "SOLICITUD_RANGO_NO_ASIGNADO";	
	public static final String PRINT_OUTPUT_PARAM_NAME = "PRINT_OUTPUT_FOLDER";
	public static final String PRINT_TEMPLATES_PARAM_NAME = "PRINT_TEMPLATES_FOLDER";
	public static final String LOG_FOLDER_PARAM_NAME = "LOG_FOLDER";
	public static final String TEMP_FOLDER_PARAM_NAME = "TEMP_FOLDER";
	public static final String CARPETA_AEDITAR_PARAM_NAME = "CARPETA_AEDITAR";
	public static final String CARPETA_BORRADORES_PARAM_NAME = "CARPETA_BORRADORES";
	public static final String CARPETA_PLANTILLAS_PARAM_NAME = "CARPETA_PLANTILLAS";	
	public static final String MOSTRAR_NUMERACION_INTERNA_PARAM_NAME = "MOSTRAR_NUMERACION_INTERNA";
	
	public static final String NOMBRE_EMPRESA_PARAM_NAME = "NOMBRE_EMPRESA";
	public static final String BACKUP_FOLDER_PARAM_NAME = "BACKUP_FOLDER";
	public static final String CONTROL_FOLDER_PARAM_NAME = "CONTROL_FOLDER";
	
	public static final String URL_RNCENTRAL_ENVIO_SOBRES_CFE_LP_PARAM_NAME = "URL_RNCENTRAL_ENVIO_SOBRES_CFE_LP";	
	public static final String URL_RNCENTRAL_ENVIO_SOBRES_CFE_HP_PARAM_NAME = "URL_RNCENTRAL_ENVIO_SOBRES_CFE_HP";
	public static final String URL_RNCENTRAL_ENVIO_REPORTES_DIARIOS_PARAM_NAME = "URL_RNCENTRAL_ENVIO_REPORTES_DIARIOS";
	public static final String URL_RNCENTRAL_ENVIO_ACUSES_PARAM_NAME = "URL_RNCENTRAL_ENVIO_ACUSES";
	public static final String URL_RNCENTRAL_ENVIO_ERRORES_PARAM_NAME = "URL_RNCENTRAL_ENVIO_ERRORES";
	public static final String URL_RNCENTRAL_ENVIO_STATUS_PARAM_NAME = "URL_RNCENTRAL_ENVIO_STATUS";

	public static final String URL_RNCENTRAL_RECEPCION_SOBRES_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_SOBRES";
	public static final String URL_RNCENTRAL_RECEPCION_ACUSES_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_ACUSES";
	public static final String URL_RNCENTRAL_ENVIO_CONFIRMACION_ACUSES_PARAM_NAME = "URL_RNCENTRAL_ENVIO_CONFIRMACION_ACUSES";
	public static final String URL_RNCENTRAL_RECEPCION_RECHAZOS_DGI_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_RECHAZOS_DGI";
	public static final String URL_RNCENTRAL_CONF_RECHAZOS_DGI_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_CONF_RECHAZOS_DGI";	
	public static final String URL_RNCENTRAL_RECEPCION_USUARIOS_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_USUARIOS";
	public static final String URL_RNCENTRAL_RECEPCION_RECEPTORES_ELECTRONICOS_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_RECEPTORES_ELECTRONICOS";
	public static final String URL_RNCENTRAL_MONITOREO_PARAM_NAME = "URL_RNCENTRAL_MONITOREO";
	public static final String URL_RNCENTRAL_VALORES_UI_PARAM_NAME = "URL_RNCENTRAL_VALORES_UI";	

	public static final String URL_WS_DGI_PARAM_NAME = "URL_WS_DGI";
	public static final String URL_WS_CONSULTA_DGI_PARAM_NAME = "URL_WS_CONSULTA_DGI";
	public static final String WS_SEGUROS = "WS_SEGUROS";
	
	public static final String CANTIDAD_CFES_SOBRE_PARAM_NAME = "CANTIDAD_CFES_SOBRE";
	public static final String CANTIDAD_RESULTADOS_BUSQUEDA_PARAM_NAME = "CANTIDAD_RESULTADOS_BUSQUEDA";
	public static final String MOSTRAR_AVISO_CFE_RONDANET_EN_FORMATOS_PARAM_NAME = "MOSTRAR_AVISO_CFE_RONDANET_EN_FORMATOS";
	public static final String MAX_SIZE_SOBRE_DGI_PARAM_NAME = "MAX_SIZE_SOBRE_DGI";
	public static final String KEYSTORE_FILENAME_PARAM_NAME = "KEYSTORE_FILENAME";
	public static final String KEYSTORE_PASSWORD_PARAM_NAME = "KEYSTORE_PASSWORD";
	public static final String KEY_NAME_PARAM_NAME = "KEY_NAME";
	public static final String KEY_PASSWORD_PARAM_NAME = "KEY_PASSWORD";
	public static final String RUT_DGI_PARAM_NAME = "RUT_DGI";
	public static final String RUT_EMISOR_PARAM_NAME = "RUT_EMISOR";
	public static final String ID_EMISOR_PARAM_NAME = "ID_EMISOR";
	public static final String PASSWORD_RNC_PARAM_NAME = "PASSWORD_RNC";
	
	public static final String MAIL_SMTP_USER_PARAM_NAME = "MAIL_SMTP_USER";
	public static final String MAIL_SMTP_PASSWORD_PARAM_NAME = "MAIL_SMTP_PASSWORD";
	public static final String MAIL_SMTP_HOST_PARAM_NAME = "MAIL_SMTP_HOST";
	public static final String MAIL_SMTP_PUERTO_PARAM_NAME = "MAIL_SMTP_PUERTO";
	public static final String MAIL_SMTP_AUTH_PARAM_NAME = "MAIL_SMTP_AUTH";
	public static final String MAIL_SMTP_TLS_PARAM_NAME = "MAIL_SMTP_TLS";
	public static final String MAIL_SMTP_SSL_PARAM_NAME = "MAIL_SMTP_SSL";
	public static final String MAIL_ACCESS_PROTOCOL = "MAIL_ACCESS_PROTOCOL";
	public static final String MAIL_ACCESS_USER_PARAM_NAME = "MAIL_ACCESS_USER";
	public static final String MAIL_ACCESS_PASSWORD_PARAM_NAME = "MAIL_ACCESS_PASSWORD";
	public static final String MAIL_ACCESS_HOST_PARAM_NAME = "MAIL_ACCESS_HOST";
	public static final String MAIL_ACCESS_PUERTO_PARAM_NAME = "MAIL_ACCESS_PUERTO";
	public static final String MAIL_ACCESS_AUTH_PARAM_NAME = "MAIL_ACCESS_AUTH";
	public static final String MAIL_ACCESS_SSL_PARAM_NAME = "MAIL_ACCESS_SSL";
	public static final String MAIL_ACCESS_INBOX_PARAM_NAME = "MAIL_ACCESS_INBOX";
		
	public static final String CFEADENDA_SCHEMA_VALIDATION_FILE_PARAM_NAME = "CFEADENDA_SCHEMA_VALIDATION_FILE";
	public static final String SOBRE_EMPRESAS_SCHEMA_VALIDATION_FILE_PARAM_NAME = "SOBRE_EMPRESAS_SCHEMA_VALIDATION_FILE";
	
	public static final String NUMERO_AÑO_RESOLUCION = "NUMERO_AÑO_RESOLUCION";
	public static final String NUMERO_AÑO_RESOLUCION_RESGUARDOS = "NUMERO_AÑO_RESOLUCION_RESGUARDOS";
	
	public static final String LOGO_PATH = "LOGO";
	
	public static final String GENERATE_PDF_FILE_PARAM_NAME = "GENERATE_PDF_FILE";
	public static final String GENERATE_PDF_FILE_RECIBIDOS_PARAM_NAME = "GENERATE_PDF_FILE_RECIBIDOS";
	public static final String GENERATE_PDF_BASE_PARAM_NAME = "GENERATE_PDF_BASE";
	
	public static final String HABILITAR_ALARMAS = "HABILITAR_ALARMAS";
	public static final String VALIDAR_TOTALES = "VALIDAR_TOTALES";
	public static final String VALIDAR_CALCULO_IVA = "VALIDAR_CALCULO_IVA";
	public static final String TOLERANCIA_CALCULO_IVA = "TOLERANCIA_CALCULO_IVA";	
	public static final String GUARDAR_ACK_INERNOS = "GUARDAR_ACK_INTERNOS";

	public static final String MODO_CERTIFICACION_PARAM_NAME = "MODO_CERTIFICACION";
	public static final String HABILITAR_CFE_ENTRY_PARAM_NAME = "HABILITAR_CFE_ENTRY";
	public static final String GUARDAR_REPORTE_DIARIO = "GUARDAR_REPORTE_DIARIO";
	
	public static final String GENERAR_LISTA_CORRESPONDENCIA_NUMEROS_PARAM_NAME = "GENERAR_LISTA_CORRESPONDENCIA_NUMEROS";
	
	//Parámetros de email
	public static final String POP_HOST_PARAM_NAME = "POP_HOST";
	public static final String POP_PORT_PARAM_NAME ="POP_PORT";
	public static final String POP_USER_PARAM_NAME = "POP_USER";
	public static final String POP_PASS_PARAM_NAME = "POP_PASS";
	public static final String POP_SSL_PARAM_NAME = "POP_SSL";
	public static final String SMTP_HOST_PARAM_NAME = "SMTP_HOST";
	public static final String SMTP_PORT_PARAM_NAME = "SMTP_PORT";
	public static final String SMTP_USER_PARAM_NAME = "SMTP_USER";
	public static final String SMTP_PASS_PARAM_NAME = "SMTP_PASS";
	public static final String SMTP_REQUIERE_AUTENTICACION_PARAM_NAME = "SMTP_REQUIERE_AUTENTICACION";
	public static final String STMP_REQUIERE_TLS_PARAM_NAME = "STMP_REQUIERE_TLS";
	public static final String POP_ANTES_DE_ENVIAR_PARAM_NAME = "POP_ANTES_DE_ENVIAR";
	
	//Parametros de tiempo de ejecuci�n de tareas
	public static final String TIEMPO_DEPURACION_CFE_ENVIADOS_PARAM_NAME = "TIEMPO_DEPURACION_CFE_ENVIADOS";
	public static final String TIEMPO_DEPURACION_CFE_RECIBIDOS_PARAM_NAME = "TIEMPO_DEPURACION_CFE_RECIBIDOS";
	public static final String TIEMPO_PROCESO_DEPURACION_PARAM_NAME = "TIEMPO_PROCESO_DEPURACION";
	public static final String TIEMPO_DEPURACION_ACK_INTEROS_PARAM_NAME = "TIEMPO_DEPURACION_ACK_INTERNOS";
 	public static final String TIEMPO_DEPURACION_NO_ENVIADOS_PARAM_NAME = "TIEMPO_DEPURACION_NO_ENVIADOS";
	public static final String TIEMPO_DEPURACION_ALARMAS_PARAM_NAME = "TIEMPO_DEPURACION_ALARMAS";
	public static final String TIEMPO_DEPURACION_LOGS_USUARIO_PARAM_NAME = "TIEMPO_DEPURACION_LOGS_USUARIO";
	public static final String TIEMPO_DEPURACION_LOGS_PARAM_NAME = "TIEMPO_DEPURACION_LOGS";
	public static final String TIEMPO_GUARDAR_TABLA_CORRESPONDENCIA_PARAM_NAME = "TIEMPO_GUARDAR_TABLA_CORRESPONDENCIA";
	public static final String TIEMPO_PROCESO_RECEPCION_MAILS = "TIEMPO_PROCESO_RECEPCION_MAILS";
	public static final String TIEMPO_PUBLICACION_WEB = "TIEMPO_PUBLICACION_WEB";	
	
	public static final String TIEMPO_PROCESAMIENTO_CFE_HP_PARAM_NAME = "TIEMPO_PROCESAMIENTO_CFE_HP"; 
	public static final String TIEMPO_PROCESAMIENTO_CFE_LP_PARAM_NAME = "TIEMPO_PROCESAMIENTO_CFE_LP";
	public static final String TIEMPO_ENSOBRADO_CFE_HP_PARAM_NAME = "TIEMPO_ENSOBRADO_CFE_HP"; 
	public static final String TIEMPO_ENSOBRADO_CFE_LP_PARAM_NAME = "TIEMPO_ENSOBRADO_CFE_LP";
	public static final String TIEMPO_ENVIO_CFE_HP_PARAM_NAME = "TIEMPO_ENVIO_CFE_HP"; 
	public static final String TIEMPO_ENVIO_CFE_LP_PARAM_NAME = "TIEMPO_ENVIO_CFE_LP";

	public static final String TIEMPO_RECEPCION_CFE_PARAM_NAME = "TIEMPO_RECEPCION_CFE";
	public static final String TIEMPO_RECEPCION_ACUSES_PARAM_NAME = "TIEMPO_RECEPCION_ACUSES";	
	public static final String TIEMPO_GENERACION_ACUSES_PARAM_NAME = "TIEMPO_GENERACION_ACUSES";
	public static final String TIEMPO_ENVIO_ACUSES_PARAM_NAME = "TIEMPO_ENVIO_ACUSES";
	public static final String TIEMPO_SOLICITUD_RANGO_CAE_PARAM_NAME = "TIEMPO_SOLICITUD_RANGO_CAE";
	public static final String TIEMPO_ENVIO_ALARMAS_PARAM_NAME = "TIEMPO_ENVIO_ALARMAS";
	public static final String TIEMPO_GENERADOR_REPORTES_NAME = "TIEMPO_GENERADOR_REPORTES_DIARIOS";
	public static final String TIEMPO_ENVIO_REPORTES_NAME = "TIEMPO_ENVIO_REPORTES_DIARIOS";
	public static final String TIEMPO_PROCESO_GENERAR_CORRESP_NAME = "TIEMPO_PROCESO_GENERAR_CORRESP";
	public static final String TIEMPO_ENVIO_STATUS_PARAM_NAME = "TIEMPO_ENVIO_STATUS";
	
	// Parametros de firma
	public static final String CRYPTOGRAPHIC_CONFIGURATION_PARAM_NAME = "CRYPTOGRAPHIC_CONFIGURATION";
	public static final String CRYPTO_KEYSTORE_PROVIDER_PARAM_NAME = "CRYPTO_KEYSTORE_PROVIDER";
	public static final String CRYPTO_KEYSTORE_TYPE_PARAM_NAME = "CRYPTO_KEYSTORE_TYPE";
	
	// Parametros de control de Reportes diarios
	public static final String ENVIAR_ALARMA_REPORTE_DIARIO_PARAM_NAME = "ENVIAR_ALARMA_REPORTE_DIARIO";
	public static final String ENVIAR_REPORTE_DIARIO_AUTOMATICO_PARAM_NAME = "ENVIAR_REPORTE_DIARIO_AUTOMATICO";
	public static final String HORA_ALARMA_REPORTE_DIARIO_PARAM_NAME = "HORA_ALARMA_REPORTE_DIARIO";
	public static final String HORA_ENVIO_REPORTE_DIARIO_PARAM_NAME = "HORA_ENVIO_REPORTE_DIARIO";
	public static final String DIAS_ENVIO_REPORTE_DIARIO_PARAM_NAME = "DIAS_ENVIO_REPORTE_DIARIO";
	public static final String DIAS_ENVIO_ALARMA_REPORTE_DIARIO_PARAM_NAME = "DIAS_ENVIO_ALARMA_REPORTE_DIARIO";
	
	public static final String IMPRIMIR_CFE_ANTES_ENVIAR_DGI_PARAM_NAME = "IMPRIMIR_CFE_ANTES_ENVIAR_DGI";
	
	// Par�metros de control para la impresi�n de lotes
	public static final String MODO_IMPRESION_LOTES_PARAM_NAME = "MODO_IMPRESION_LOTES";
	
	//Par�metros para la carga de CAES
	public static final String CAES_CREATED_FOLDER_PARAM_NAME = "CAEs_CREATED_FOLDER";
	public static final String CAES_NOT_CREATED_FOLDER_PARAM_NAME = "CAEs_NOT_CREATED_FOLDER";
	public static final String CAES_TO_CREATE_FOLDER_PARAM_NAME = "CAEs_TO_CREATE_FOLDER";
	
	//Par�metros para envio de alertas fecha vencimiento certificados
	public static final String DIAS_ALARMA_CERTIFICADOS_PARAM_NAME= "DAYS_SEND_ALERTS";
	public static final String DIAS_ALARMA_VENCIMIENTO_CAE_PARAM_NAME= "DIAS_ALERTA_VENCIMIENTO_CAE";
	public static final String HORA_ALARMA_CERTIFICADOS_PARAM_NAME= "SEND_MAIL_TIME";	
	public static final String HORA_ALARMA_CAES_PARAM_NAME= "HORA_ALARMA_CAES";	
	public static final String VALIDAR_CERTIFICADOS_PARAM_NAME= "VALIDATE_CRETIFICATES";
	
	public static final String ENVIAR_ALARMA_VENCIMIENTO_CAE_PARAM_NAME = "ENVIAR_ALARMA_VENCIMIENTO_CAE";
	
	public static final String RAZON_SOCIALL_PARAM_NAME = "RAZON_SOCIAL";
	public static final String CIUDADL_PARAM_NAME = "CIUDAD";
	public static final String DEPARTAMENTO_PARAM_NAME = "DEPARTAMENTO";
	
	public static final String REVISAR_STOCKS_PARAM_NAME = "REVISAR_STOCKS";
	public static final String REVISAR_STOCKS_CRON_SCHEDULE_PARAM_NAME = "REVISAR_STOCKS_CRON_SCHEDULE";
	
	//Parametro tipo de app
	public static final String TIPO_APLICACION ="TIPO_APLICACION";
	
	public static final String AGREGAR_CAE_TAG_CFC_PARAM_NAME = "AGREGAR_CAE_TAG_CFC"; 
	public static final String AGREGAR_CAE_TAG_CFE_PARAM_NAME = "AGREGAR_CAE_TAG_CFE"; 
	
	public static final String SOCKET_CONNECTION_TIMEOUT_PARAM_NAME = "SOCKET_CONNECTION_TIMEOUT";
	public static final String SOCKET_DATA_TIMEOUT_PARAM_NAME = "SOCKET_DATA_TIMEOUT";
	
	public static final String PROXY_HOST_PARAM_NAME = "PROXY_HOST";
	public static final String PROXY_PORT_PARAM_NAME = "PROXY_PORT";
	public static final String PROXY_USER_PARAM_NAME = "PROXY_USER";
	public static final String PROXY_PASS_PARAM_NAME = "PROXY_PASS";
	public static final String PROXY_DOMAIN_PARAM_NAME = "PROXY_DOMAIN";
	
	public static final String URL_DGI_PUBLICACION_WEB_PARAM_NAME = "URL_DGI_PUBLICACION_WEB";
	public static final String URL_EMPRESA_PUBLICACION_WEB_PARAM_NAME = "URL_EMPRESA_PUBLICACION_WEB"; 
	
	public static final String TIMEOUT_WEBSERVICE_DGI_PARAM_NAME = "TIMEOUT_WEBSERVICE_DGI"; 
	
	public static final String ALARMAS_CANTIDAD_PROX_BASE_PARAM_NAME = "ALARMAS_CANTIDAD_PROX_BASE";
	public static final String ALARMAS_PROXIMO_ENVIO_MULT_SUMA_PARAM_NAME = "ALARMAS_PROXIMO_ENVIO_MULT_SUMA";
	public static final String ALARMAS_PROXIMO_ENVIO_MULT_RESTA_PARAM_NAME = "ALARMAS_PROXIMO_ENVIO_MULT_RESTA";
	public static final String ALARMAS_MAX_TIEMPO_SIN_ENVIAR_PARAM_NAME = "ALARMAS_MAX_TIEMPO_SIN_ENVIAR";
	public static final String ALARMAS_TIEMPO_DEPURACION_HASH_PARAM_NAME = "ALARMAS_CANTIDAD_PROX_BASE";
	
	public static final String INTENTOS_LECTURA_CFE_PARAM_NAME = "INTENTOS_LECTURA_CFE";
	public static final String HABILITAR_DEBUG_MAIL_PARAM_NAME = "HABILITAR_DEBUG_MAIL";
	
	public static final String TOLERANCIA_TOTALES_PARAM_NAME = "TOLERANCIA_TOTALES";
	public static final String LICENCIA_PARAM_NAME = "LICENCIA";
	public static final String FECHA_INSTALACION_PARAM_NAME = "QG2w0b2G9TkkITznj6a+MteGwbHWLrHb";
	public static final String TELEFONO1_EMISOR_PARAM_NAME = "TELEFONO1_EMISOR";
	public static final String TELEFONO2_EMISOR_PARAM_NAME = "TELEFONO2_EMISOR";
	public static final String MAX_CFE_PROCESADOS_HP_PARAM_NAME = "MAX_CFE_PROCESADOS_HP";
	public static final String MAX_CFE_PROCESADOS_LP_PARAM_NAME = "MAX_CFE_PROCESADOS_LP";
	public static final String MAIL_SMTP_FROM_PARAM_NAME = "MAIL_SMTP_FROM";
	
	public static final String HABILITAR_RECIBOS_PARAM_NAME = "HABILITAR_RECIBOS";
	
	public static final String RESPUESTA_WS_STATUS_NO_CORRESPONDE_ENVIAR_DGI_PARAM_NAME = "RESPUESTA_WS_STATUS_NO_CORRESPONDE_ENVIAR_DGI";   
	public static final String FREE_SHOP_PARAM_NAME = "FREE_SHOP";
	
	public static final String TEMPLATE_NOM_CFE_EMITIDO_PARAM_NAME = "TEMPLATE_NOM_CFE_EMITIDO";
	public static final String TEMPLATE_NOM_CFE_RECIBIDO_PARAM_NAME = "TEMPLATE_NOM_CFE_RECIBIDO";
	
	public static final String FECHA_PUBLICACION_XSD_PARAM_NAME = "FECHA_PUBLICACION_XSD";
	
	public static final String VERSION_PARAM_NAME = "VERSION";
	public static final String CARPETA_ACTUALIZACIONES_PARAM_NAME = "CARPETA_ACTUALIZACIONES";
		
	public static final String IMPRESION_INDIVIDUAL_PARAM_NAME = "IMPRESION_INDIVIDUAL";
	
	public static final String HABILITAR_UTILES_ADMIN_PARAM_NAME = "HABILITAR_UTILES_ADMIN";
	
	public static final String ACTUALIZACION_HOST_FTPS_PARAM_NAME = "ACTUALIZACION_HOST_FTPS";
	public static final String ACTUALIZACION_USER_FTPS_PARAM_NAME = "ACTUALIZACION_USER_FTPS";
	public static final String ACTUALIZACION_PASS_FTPS_PARAM_NAME = "ACTUALIZACION_PASS_FTPS";
	
	public static final String CTRL_SUMAS_DE_ITEMS_PARAM_NAME = "CTRL_SUMAS_DE_ITEMS";
	public static final String CTRL_RET_PER_CREDFISC_PARAM_NAME = "CTRL_RET_PER_CREDFISC";
	public static final String CTRL_SUMA_NOFACTURABLES_PARAM_NAME = "CTRL_SUMA_NOFACTURABLES";
	public static final String CTRL_PROD_SERVICIOS_PARAM_NAME = "CTRL_PROD_SERVICIOS";
	public static final String CTRL_SECUENCIAS_PARAM_NAME = "CTRL_SECUENCIAS";
	public static final String CTRL_COMP_FISCAL_PARAM_NAME = "CTRL_COMP_FISCAL";
	public static final String CTRL_VALIDAR_SUCURSALES_PARAM_NAME = "CTRL_VALIDAR_SUCURSALES";
	public static final String VALIDAR_NIE_PARAM_NAME = "VALIDAR_NIE";

	public static final String INFO_ADICIONAL_RECEP_DATA_ENTRY_VISIBLE_PARAM_NAME = "INFO_ADICIONAL_RECEP_DATA_ENTRY_VISIBLE";
	public static final String INFO_ADICIONAL_EMISOR_DATA_ENTRY_VISIBLE_PARAM_NAME = "INFO_ADICIONAL_EMISOR_DATA_ENTRY_VISIBLE";
	public static final String INFO_ADICIONAL_EMISOR_DATA_ENTRY_DEFECTO_PARAM_NAME = "INFO_ADICIONAL_EMISOR_DATA_ENTRY_DEFECTO";
	public static final String COND_DE_PAGO_DATA_ENTRY_VISIBLE_PARAM_NAME = "COND_DE_PAGO_DATA_ENTRY_VISIBLE";
	public static final String COND_DE_ENVIO_DATA_ENTRY_VISIBLE_PARAM_NAME = "COND_DE_ENVIO_DATA_ENTRY_VISIBLE";
	
	public static final String MODO_CONTROL_RECIBIDOS_PARAM_NAME = "MODO_CONTROL_RECIBIDOS";
	
	public static final String CONTROLAR_ENVIO_REPORTE_PARAM_NAME = "CONTROLAR_ENVIO_REPORTE";
	
	public static final String MESES_ALMACENAMIENTO_SIN_COSTO_PARAM_NAME = "MESES_ALMACENAMIENTO_SIN_COSTO";
	public static final String TIEMPO_ESPERA_PROCESO_PAQUETES_MENSUALES_PARAM_NAME = "TIEMPO_ESPERA_PROCESO_PAQUETES_MENSUALES";
	public static final String TAMANO_BLOQUE_PROCESO_PAQUETES_MENSUALES_PARAM_NAME = "TAMANO_BLOQUE_PROCESO_PAQUETES_MENSUALES";
	
	public static final String CTRL_REM_RES_REFERENCIAS_PARAM_NAME = "CTRL_REM_RES_REFERENCIAS";
	
	public static final String ACCESO_ADMIN_ACTUALIZADOR_PARAM_NAME = "ACCESO_ADMIN_ACTUALIZADOR";
	
	// para servicios externos 17.05.25
	public static final String SERVICIOS_EXTERNOS_END_POINT_PARAM_NAME = "SERVICIOS_EXTERNOS_END_POINT"; 
	public static final String SERVICIOS_EXTERNOS_USUARIO_PARAM_NAME = "SERVICIOS_EXTERNOS_USUARIO"; 
	public static final String SERVICIOS_EXTERNOS_PASSWORD_PARAM_NAME = "SERVICIOS_EXTERNOS_PASSWORD"; 
	
	// parametrizamos cantidad de intentos fallidos y minutos bloqueo
	public static final String MAX_INTENTOS_LOGIN_FALLIDO_PARAM_NAME = "MAX_INTENTOS_LOGIN_FALLIDO";
	public static final String MINUTOS_BLOQUEO_LOGIN_PARAM_NAME = "MINUTOS_BLOQUEO_LOGIN";
	
	// parametros para el envio de mail a clientes desde el data entry
	public static final String MAIL_CLIENTE_ASUNTO_PARAM_NAME = "MAIL_CLIENTE_ASUNTO";
	public static final String MAIL_CLIENTE_CUERPO_PARAM_NAME = "MAIL_CLIENTE_CUERPO";
	public static final String MAIL_CLIENTE_IS_ACTIVAR_PARAM_NAME = "MAIL_CLIENTE_IS_ACTIVAR";
	
	public static final String DATA_ENTRY_LAST_IS_CREDITO_PARAM_NAME = "DATA_ENTRY_LAST_IS_CREDITO"; 
	
	
	private String idParametro;
	private String descripcion;
	private String valorString;
	private Integer valorInteger;
	private Boolean valorBool;
	private Date valorDate;
	private String valorPassword;
	private BigDecimal valorNumerico;

	@Id
	@Column(name = "id_parametro", unique = true, nullable = false, length = 80)
	public String getIdParametro() {
		return this.idParametro;
	}

	public void setIdParametro(String idParametro) {
		this.idParametro = idParametro;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "valor_string")
	public String getValorString() {
		return this.valorString;
	}

	public void setValorString(String valorString) {
		this.valorString = valorString;
	}

	@Column(name = "valor_integer")
	public Integer getValorInteger() {
		return this.valorInteger;
	}

	public void setValorInteger(Integer valorInteger) {
		this.valorInteger = valorInteger;
	}

	@Column(name = "valor_bool")
	public Boolean getValorBool() {
		return this.valorBool;
	}

	public void setValorBool(Boolean valorBool) {
		this.valorBool = valorBool;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valor_date", length = 29)
	public Date getValorDate() {
		return this.valorDate;
	}

	public void setValorDate(Date valorDate) {
		this.valorDate = valorDate;
	}

	@Column(name = "valor_password")
	public String getValorPassword() {
		return this.valorPassword;
	}

	/**
	 * Si se utiliza este m�todo las passwords que se graban en la base de datos quedan sin encriptar
	 * @param valorPassword
	 */
	public void setValorPassword(String valorPassword) {
		this.valorPassword = valorPassword;
	}

	@Column(name = "valor_numerico")
	public BigDecimal getValorNumerico() {
		return valorNumerico;
	}

	public void setValorNumerico(BigDecimal valorNumerico) {
		this.valorNumerico = valorNumerico;
	}

	@Transient
	public String getValor(){
		return getValorString();
	}
}
