package ctes;

public final class Ctes {
	
	public static final String RAZON_SOCIALL_PARAM_NAME = "RAZON_SOCIAL";
	public static final String CIUDADL_PARAM_NAME = "CIUDAD";
	public static final String DEPARTAMENTO_PARAM_NAME = "DEPARTAMENTO";
	public static final String TELEFONO1_EMISOR_PARAM_NAME = "TELEFONO1_EMISOR";
	public static final String TELEFONO2_EMISOR_PARAM_NAME = "TELEFONO2_EMISOR";
	public static final String NOMBRE_EMPRESA_PARAM_NAME = "NOMBRE_EMPRESA";
	public static final String RUT_EMISOR_PARAM_NAME = "RUT_EMISOR";
	
	public static final String HOME_FOLDER_PARAM_NAME = "HOME_FOLDER";
	public static final String HOME_APP_FOLDER_PARAM_NAME = "HOME_APP_FOLDER";
	public static final String LOGO_PATH = "LOGO";
	
	public static final String KEYSTORE_FILENAME_PARAM_NAME = "KEYSTORE_FILENAME";
	
	public static final String PASSWORD_RNC_PARAM_NAME = "PASSWORD_RNC";
	
	/* */
	public static final String TIPO_APLICACION = "TIPO_APLICACION";
	
	public static final String ACTUALIZACION_USER_FTPS_PARAM_NAME = "ACTUALIZACION_USER_FTPS";
	public static final String ACTUALIZACION_PASS_FTPS_PARAM_NAME = "ACTUALIZACION_PASS_FTPS";
	
	public static final String URL_RNCENTRAL_ENVIO_SOBRES_CFE_LP_PARAM_NAME = "URL_RNCENTRAL_ENVIO_SOBRES_CFE_LP";	
	public static final String URL_RNCENTRAL_ENVIO_SOBRES_CFE_HP_PARAM_NAME = "URL_RNCENTRAL_ENVIO_SOBRES_CFE_HP";
	public static final String URL_RNCENTRAL_ENVIO_ACUSES_PARAM_NAME = "URL_RNCENTRAL_ENVIO_ACUSES";
	public static final String URL_RNCENTRAL_ENVIO_ERRORES_PARAM_NAME = "URL_RNCENTRAL_ENVIO_ERRORES";
	public static final String URL_RNCENTRAL_ENVIO_STATUS_PARAM_NAME = "URL_RNCENTRAL_ENVIO_STATUS";
	public static final String URL_RNCENTRAL_RECEPCION_SOBRES_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_SOBRES";
	public static final String URL_RNCENTRAL_RECEPCION_ACUSES_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_ACUSES";
	public static final String URL_RNCENTRAL_ENVIO_CONFIRMACION_ACUSES_PARAM_NAME = "URL_RNCENTRAL_ENVIO_CONFIRMACION_ACUSES";
	public static final String URL_RNCENTRAL_RECEPCION_RECHAZOS_DGI_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_RECHAZOS_DGI";
	public static final String URL_RNCENTRAL_CONF_RECHAZOS_DGI_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_CONF_RECHAZOS_DGI";	
	public static final String URL_RNCENTRAL_RECEPCION_USUARIOS_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_USUARIOS";
	public static final String URL_RNCENTRAL_RECEPCION_RECEPTORES_ELECTRONICOS_PARAM_NAME = "URL_RNCENTRAL_RECEPCION_RECEPTORES_ELECTRONICOS";
	public static final String URL_RNCENTRAL_MONITOREO_PARAM_NAME = "URL_RNCENTRAL_MONITOREO";
	public static final String URL_RNCENTRAL_VALORES_UI_PARAM_NAME = "URL_RNCENTRAL_VALORES_UI";	

	public static final String URL_WS_DGI_PARAM_NAME = "URL_WS_DGI";
	public static final String URL_WS_CONSULTA_DGI_PARAM_NAME = "URL_WS_CONSULTA_DGI";

	public static final String HABILITAR_CFE_ENTRY_PARAM_NAME = "HABILITAR_CFE_ENTRY";
	
	//
	/*
	private static final String KEYSTORE_PASSWORD_PARAM_NAME = "KEYSTORE_PASSWORD";
	private static final String LICENCIA_PARAM_NAME = "LICENCIA"; // ?
	private static final String SERVICIOS_EXTERNOS_USUARIO_PARAM_NAME = "SERVICIOS_EXTERNOS_USUARIO"; 
	private static final String SERVICIOS_EXTERNOS_PASSWORD_PARAM_NAME = "SERVICIOS_EXTERNOS_PASSWORD";
	private static final String URL_RNCENTRAL_ENVIO_REPORTES_DIARIOS_PARAM_NAME = "URL_RNCENTRAL_ENVIO_REPORTES_DIARIOS";
	*/
}
